// src/lib/mockdata.ts

import { PartnerDashboardData } from '@/types/partner';

export const mockPartnerDashboard: PartnerDashboardData = {
  socio_info: {
    nombre: 'Juan Carlos Ramírez',
    email: 'jramírez@transportes.com',
    empresa_nombre: 'Transportes Rápidos S.A.',
    empresa_id: 'empresa-uuid-1',
  },
  resumen: {
    total_buses: 12,
    buses_operativos_ahora: 8,
    conductores_activos_hoy: 15,
    alertas_criticas_sin_atender: 2,
  },
  buses: [
    {
      id: 'bus-1',
      placa: 'ABC-123',
      numero_interno: 'BUS-001',
      estado_operativo: 'Operativo',
      conductor_actual: {
        nombre: 'Carlos Mendoza',
        cedula: '123456789',
      },
      sesion_activa: {
        id: 'sesion-1',
        inicio: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        km_recorridos: 45.3,
        velocidad_actual: 55,
      },
      ubicacion_gps: '4.6097,-74.0817',
      ultima_alerta: {
        tipo: 'Fatiga Moderada',
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        severidad: 'Media',
      },
    },
    {
      id: 'bus-2',
      placa: 'DEF-456',
      numero_interno: 'BUS-002',
      estado_operativo: 'Operativo',
      conductor_actual: {
        nombre: 'Ana García',
        cedula: '987654321',
      },
      sesion_activa: {
        id: 'sesion-2',
        inicio: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
        km_recorridos: 32.8,
        velocidad_actual: 48,
      },
      ubicacion_gps: '4.5981,-74.0758',
      ultima_alerta: null,
    },
    {
      id: 'bus-3',
      placa: 'GHI-789',
      numero_interno: 'BUS-003',
      estado_operativo: 'Operativo',
      conductor_actual: {
        nombre: 'Luis Torres',
        cedula: '456789123',
      },
      sesion_activa: {
        id: 'sesion-3',
        inicio: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        km_recorridos: 67.5,
        velocidad_actual: 62,
      },
      ubicacion_gps: '4.6283,-74.0641',
      ultima_alerta: {
        tipo: 'Distracción',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        severidad: 'Alta',
      },
    },
    {
      id: 'bus-4',
      placa: 'JKL-012',
      numero_interno: 'BUS-004',
      estado_operativo: 'Mantenimiento',
      conductor_actual: null,
      sesion_activa: null,
      ubicacion_gps: null,
      ultima_alerta: null,
    },
  ],
  alertas_recientes: [
    {
      id: 'alerta-1',
      tipo: 'Fatiga Severa',
      severidad: 'Crítica',
      conductor_nombre: 'Carlos Mendoza',
      bus_placa: 'ABC-123',
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      atendida: false,
      descripcion: 'Conductor presenta signos de fatiga severa. Requiere descanso inmediato.',
    },
    {
      id: 'alerta-2',
      tipo: 'Velocidad Excesiva',
      severidad: 'Crítica',
      conductor_nombre: 'Luis Torres',
      bus_placa: 'GHI-789',
      timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      atendida: false,
      descripcion: 'Velocidad detectada: 95 km/h en zona de 60 km/h.',
    },
    {
      id: 'alerta-3',
      tipo: 'Distracción',
      severidad: 'Alta',
      conductor_nombre: 'Ana García',
      bus_placa: 'DEF-456',
      timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      atendida: true,
      descripcion: 'Múltiples distracciones detectadas en los últimos 10 minutos.',
    },
    {
      id: 'alerta-4',
      tipo: 'Frenado Brusco',
      severidad: 'Media',
      conductor_nombre: 'Pedro Ramírez',
      bus_placa: 'MNO-345',
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      atendida: true,
      descripcion: 'Frenado brusco detectado. Revisar condiciones de la ruta.',
    },
    {
      id: 'alerta-5',
      tipo: 'Fatiga Moderada',
      severidad: 'Media',
      conductor_nombre: 'Carlos Mendoza',
      bus_placa: 'ABC-123',
      timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      atendida: true,
      descripcion: 'Signos de fatiga moderada detectados.',
    },
  ],
  conductores_destacados: [
    {
      id: 'conductor-1',
      nombre: 'Ana García',
      cedula: '987654321',
      foto_url: null,
      calificacion_mes: 9.5,
      horas_conducidas_mes: 168,
      alertas_mes: 2,
    },
    {
      id: 'conductor-2',
      nombre: 'Luis Torres',
      cedula: '456789123',
      foto_url: null,
      calificacion_mes: 9.2,
      horas_conducidas_mes: 175,
      alertas_mes: 5,
    },
    {
      id: 'conductor-3',
      nombre: 'María Rodríguez',
      cedula: '789456123',
      foto_url: null,
      calificacion_mes: 9.0,
      horas_conducidas_mes: 160,
      alertas_mes: 3,
    },
  ],
  metricas_hoy: {
    total_km_recorridos: 1254.8,
    promedio_velocidad: 52.3,
    total_alertas_generadas: 18,
    eficiencia_operativa: 94.5,
  },
};